### ISSUE TITLE
Question regarding normalization

### ISSUE THREAD

**Issue by venetisgr** [sainathadapa/kaggle-freesound-audio-tagging#2]
I would like to apologize in advance if this is the wrong place to ask a question. I have a question regarding the data normalization and the pca feature creation. If your dataset had a shape of (batches,mfcc,samples) how would you apply the transforms I mentioned before. In your code, are you normalizing and extracting pca features for each training example alone ?

**Comment by sainathadapa** [comment]
Sure, you can ask questions here. I didn't fully understand your question though. Can you elaborate?

**Comment by venetisgr** [comment]
Yes of course, when you normalized the samples, did you normalize each sample individually given its current values or did you check all the available samples to get their mean for example and then normalize?

**Comment by sainathadapa** [comment]
For PCA, the pre-processing step includes `StandardScaler` which standardizes the features. For the Mel-features, I didn't explicitly normalize standardize the data, but I used `BatchNormalization` as the initial layer, which kinda does this for me automatically, but based on mini-batch statistics.

**Comment by sainathadapa** [comment]
feel free to ask any other questions you may have
